# Generated by Django 5.2.1 on 2025-06-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('hotel_owner', 'Hotel Owner')], max_length=20),
        ),
    ]
